# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 8, 29, 13, 426000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
